version: "3.9"
services:
  DreamboothTrainInference:
    image: enlightaidreambooth:latest
    build: .
    stdin_open: true 
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./Dreambooth:/code
    environment:
      - enlight.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]


