accelerate launch --main_process_por 28900 train_dreambooth768.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1"  \
  --instance_data_dir="INPUT" \
  --output_dir="OUTPUT" \
  --train_text_encoder \
  --instance_prompt="a photo of a sksjacket"  \
  --resolution=768 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=2.0e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400
